name: Continues Integration

on:
  push:
    branches:
      - '6.x'
      - 'master'
  pull_request:
    branches:
      - '6.x'
      - 'master'

env:
  PYTHON_VERSION: '3.10'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Run lint
        run: make lint
